name: "auto-release"

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: "write"
  contents: "write"
  packages: "write"
  pull-requests: "read"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
  
  notify_on_telegram:
    name: "Notify on Telegram"
    runs-on: "ubuntu-latest"
    needs: "tagged-release"
    steps:
      - name: "Send Telegram message"
        uses: "appleboy/telegram-action@master"
        with:
          to: "${{ secrets.TELEGRAM_TO }}"
          token: "${{ secrets.TELEGRAM_TOKEN }}"
          format: "html"
          disable_web_page_preview: true
          message: |
            "¡Actualizaciones en <strong>${{ github.event.repository.name }}</strong>!
  
            Se ha publicado una nueva versión: <code>${{ github.ref_name }}</code>"
  
            Puedes ver los cambios en el <a href="https://github.com/${{ github.repository }}/releases/latest">changeLog</a> y consultar la <a href="https://ritsi.github.io/${{github.event.repository.name}}/">documentación</a>."